<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:property name="PI" value="3.1415926535897931" />
  <xacro:include filename="$(find wsugv_description)/urdf/common/inertials.xacro" />
  <xacro:include filename="$(find wsugv_description)/urdf/common/materials.xacro" />

  <xacro:macro name="wheel" params="prefix x_offset y_offset wheel_radius wheel_width">
    <link name="${prefix}_wheel_link">
    <xacro:default_inertial/>

    <visual>
      <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
    </collision>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <origin xyz="${x_offset} ${y_offset} ${wheel_radius}" rpy="0 0 0"/>
      <parent link="base_link" />
      <child link="${prefix}_wheel_link" />
      <axis xyz="0 1 0" />
    </joint>
  </xacro:macro>

  <xacro:macro name="wsugv" params="wheel_spacing wheel_separation wheel_radius wheel_width">
    <!-- LINKS -->
    <!-- base link -->
    <link name="base_link">

      <xacro:default_inertial/>
      <visual>
        <origin xyz="0 0 0.054505" rpy="0 0 0" />
        <geometry>
          <box size="0.24318 0.12002 0.05875" />
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0.054505" rpy="0 0 0" />
        <geometry>
          <box size="0.24318 0.12002 0.05875" />
        </geometry>
      </collision>
    </link>

    <link name="laser">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.125"/>
        <inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001" />
      </inertial>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
           <cylinder radius="0.035" length="0.025"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
           <cylinder radius="0.035" length="0.025"/>
        </geometry>
        <material name="white"/>
      </visual>
    </link>




    <!-- END LINKS -->

    <!-- JOINTS -->
    <xacro:wheel prefix="front_left"  x_offset="${wheel_spacing}" y_offset="${wheel_separation / 2}" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}"/>
    <xacro:wheel prefix="front_right" x_offset="${wheel_spacing}" y_offset="${wheel_separation / -2}" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}"/>
    <xacro:wheel prefix="mid_left"    x_offset="0" y_offset="${wheel_separation / 2}" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}"/>
    <xacro:wheel prefix="mid_right"   x_offset="0" y_offset="${wheel_separation / -2}" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}"/>
    <xacro:wheel prefix="rear_left"   x_offset="${-wheel_spacing}" y_offset="${wheel_separation / 2}" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}"/>
    <xacro:wheel prefix="rear_right"  x_offset="${-wheel_spacing}" y_offset="${wheel_separation / -2}" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}"/>

    <joint name="lidar_joint" type="fixed">
      <parent link="base_link"/>
      <child link="laser"/>
      <origin xyz="0.05 0 0.15" rpy="0 0 ${PI}"/>
    </joint>
    <!-- END JOINTS -->
  </xacro:macro>
</robot>
